// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {domain} from '../models';
import {jsontext} from '../models';

export function BuildImage(arg1:service.BuildOptions):Promise<string>;

export function CancelTask(arg1:string):Promise<void>;

export function ContainerStats(arg1:boolean):Promise<Array<domain.ContainerStats>>;

export function CreateNetwork(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function CreateVolume(arg1:string,arg2:string):Promise<string>;

export function EnvCheck():Promise<service.EnvStatus>;

export function ExportImage(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function ImportImage(arg1:string):Promise<string>;

export function InspectContainer(arg1:string):Promise<jsontext.Value>;

export function InspectImage(arg1:string):Promise<jsontext.Value>;

export function KillContainer(arg1:string,arg2:string):Promise<string>;

export function ListContainers(arg1:service.ContainerFilter):Promise<Array<domain.Container>>;

export function ListImages(arg1:boolean):Promise<Array<domain.Image>>;

export function ListNetworks():Promise<Array<domain.Network>>;

export function ListSessions():Promise<Array<domain.Session>>;

export function ListTasks():Promise<Array<service.Task>>;

export function ListVolumes():Promise<Array<domain.Volume>>;

export function LoadSettings():Promise<service.AppSettings>;

export function PruneContainers():Promise<service.PruneResult>;

export function PruneImages(arg1:boolean):Promise<service.PruneResult>;

export function PullImage(arg1:string):Promise<string>;

export function RemoveContainer(arg1:string,arg2:boolean,arg3:boolean):Promise<string>;

export function RemoveImage(arg1:string,arg2:boolean):Promise<string>;

export function RemoveNetwork(arg1:string,arg2:boolean):Promise<string>;

export function RemoveVolume(arg1:string,arg2:boolean):Promise<string>;

export function RestartContainer(arg1:string,arg2:number):Promise<string>;

export function RunContainer(arg1:service.RunContainerOptions):Promise<string>;

export function SaveSettings(arg1:service.AppSettings):Promise<service.AppSettings>;

export function StartContainer(arg1:string):Promise<string>;

export function StartLogs(arg1:string,arg2:service.LogsOptions):Promise<string>;

export function StartTerminal(arg1:string,arg2:service.ExecOptions,arg3:number,arg4:number):Promise<string>;

export function StopContainer(arg1:string,arg2:number):Promise<string>;

export function StopStream(arg1:string):Promise<void>;

export function StreamEvents():Promise<string>;

export function TagImage(arg1:string,arg2:string):Promise<string>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function TerminateSession(arg1:number):Promise<string>;

export function TestMirror(arg1:string):Promise<service.MirrorProbe>;
