// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildImage(arg1) {
  return window['go']['main']['App']['BuildImage'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ContainerStats(arg1) {
  return window['go']['main']['App']['ContainerStats'](arg1);
}

export function CreateNetwork(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateNetwork'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateVolume(arg1, arg2) {
  return window['go']['main']['App']['CreateVolume'](arg1, arg2);
}

export function EnvCheck() {
  return window['go']['main']['App']['EnvCheck']();
}

export function ExportImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportImage'](arg1, arg2, arg3);
}

export function ImportImage(arg1) {
  return window['go']['main']['App']['ImportImage'](arg1);
}

export function InspectContainer(arg1) {
  return window['go']['main']['App']['InspectContainer'](arg1);
}

export function InspectImage(arg1) {
  return window['go']['main']['App']['InspectImage'](arg1);
}

export function KillContainer(arg1, arg2) {
  return window['go']['main']['App']['KillContainer'](arg1, arg2);
}

export function ListContainers(arg1) {
  return window['go']['main']['App']['ListContainers'](arg1);
}

export function ListImages(arg1) {
  return window['go']['main']['App']['ListImages'](arg1);
}

export function ListNetworks() {
  return window['go']['main']['App']['ListNetworks']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListSessionStorage() {
  return window['go']['main']['App']['ListSessionStorage']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function PruneContainers() {
  return window['go']['main']['App']['PruneContainers']();
}

export function PruneImages(arg1) {
  return window['go']['main']['App']['PruneImages'](arg1);
}

export function PullImage(arg1) {
  return window['go']['main']['App']['PullImage'](arg1);
}

export function RemoveContainer(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2, arg3);
}

export function RemoveImage(arg1, arg2) {
  return window['go']['main']['App']['RemoveImage'](arg1, arg2);
}

export function RemoveNetwork(arg1, arg2) {
  return window['go']['main']['App']['RemoveNetwork'](arg1, arg2);
}

export function RemoveVolume(arg1, arg2) {
  return window['go']['main']['App']['RemoveVolume'](arg1, arg2);
}

export function ResetSessionStorage(arg1) {
  return window['go']['main']['App']['ResetSessionStorage'](arg1);
}

export function RestartContainer(arg1, arg2) {
  return window['go']['main']['App']['RestartContainer'](arg1, arg2);
}

export function RunContainer(arg1) {
  return window['go']['main']['App']['RunContainer'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartLogs(arg1, arg2) {
  return window['go']['main']['App']['StartLogs'](arg1, arg2);
}

export function StartTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3, arg4);
}

export function StopContainer(arg1, arg2) {
  return window['go']['main']['App']['StopContainer'](arg1, arg2);
}

export function ShrinkSessionStorage(arg1) {
  return window['go']['main']['App']['ShrinkSessionStorage'](arg1);
}

export function StopStream(arg1) {
  return window['go']['main']['App']['StopStream'](arg1);
}

export function StreamEvents() {
  return window['go']['main']['App']['StreamEvents']();
}

export function TagImage(arg1, arg2) {
  return window['go']['main']['App']['TagImage'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function TerminateSession(arg1) {
  return window['go']['main']['App']['TerminateSession'](arg1);
}

export function TestMirror(arg1) {
  return window['go']['main']['App']['TestMirror'](arg1);
}
